name: Ubuntu Made Simple
description: Simple tutorials on Ubuntu and related Linux distros!
meta_description: "Simple tutorials on Ubuntu and related Linux distros!"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://ubuntumadesimple.com'
google_analytics: 'UA-1118492-14'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://ubuntumadesimple.com/'
author:         'Ubuntu Made Simple'
